### ISSUE TITLE
What is https://md.plex.dance/cbs/shows/

### ISSUE THREAD

**Issue by brendonanderson** [sander1/CBS.bundle#3]
What is this service you are connecting to?  https://md.plex.dance/cbs/shows/

**Comment by sander1** [comment]
It's a layer between the channel and the CBS website that filters out unavailable stuff. It's done this way to prevent channel timeouts and to lower the number of total requests to CBS backends.

**Comment by brendonanderson** [comment]
Thanks for the information.  Is the code for that service available?  I'm just curious how it works.

**Comment by sander1** [comment]
This is the script that retrieves the data: https://bitbucket.org/sander1/md.plex.dance-cbs/src/master/shows.php
It is put behind an nginx caching proxy to prevent hammering on the source website.

**Comment by brendonanderson** [comment]
Thanks for the info.
